apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-system
  labels:
    app: document-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: document-system
  template:
    metadata:
      labels:
        app: document-system
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: document-system
        image: docker.io/7lawa/document-system:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: document-system-config
              key: db_host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: document-system-secrets
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: document-system-secrets
              key: db_password
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: document-system-config
              key: db_name
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: document-system-config
              key: db_port
        - name: PORT
          value: "8080"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /api/documents
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/documents
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20 