apiVersion: v1
kind: Service
metadata:
  name: document-system
  labels:
    app: document-system
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: document-system 